### ISSUE TITLE
A1 Mini - AMS Lite Failure

### ISSUE THREAD

**Issue by xDraconix** [davglass/bambu-cli#2]
Nice work! I love it!

i have a A1 Mini with AMS Lite - but at the status overview, the script stop working at this point:

`root@BambuClient:~/.config/bambu-cli# bambu-cli status speedy
Showing only, xxxx
Checking connectivity for 1 machine(s)

ID               Name    IP Address       FTP  MQTT  AMS  Nozzle  Printing  Task                      Percent  Remaining  Speed
xxxx  Speedy  192.168.178.140   ✔    ✔    A            RUNNING   Brio Schiene Duplo k ...  30%      58m        Normal

Model    Machine firm
A1 mini  01.07.21.46

/usr/lib/node_modules/bambu-cli/lib/status.js:146
                if (tray.cols.length > 1) { //Mulicolor
                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at /usr/lib/node_modules/bambu-cli/lib/status.js:146:31
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/bambu-cli/lib/status.js:127:19
    at Array.forEach (<anonymous>)
    at showDetails (/usr/lib/node_modules/bambu-cli/lib/status.js:122:13)
    at /usr/lib/node_modules/bambu-cli/lib/status.js:75:17
    at statusMQTT (/usr/lib/node_modules/bambu-cli/lib/status.js:276:9)
    at MqttClient.<anonymous> (/usr/lib/node_modules/bambu-cli/lib/status.js:271:17)
    at MqttClient.emit (node:events:514:28)
    at handlePublish (/usr/lib/node_modules/bambu-cli/node_modules/mqtt/build/lib/handlers/publish.js:97:20)
    at handle (/usr/lib/node_modules/bambu-cli/node_modules/mqtt/build/lib/handlers/index.js:28:35)
    at work (/usr/lib/node_modules/bambu-cli/node_modules/mqtt/build/lib/client.js:216:40)
    at writable._write (/usr/lib/node_modules/bambu-cli/node_modules/mqtt/build/lib/client.js:241:13)
    at writeOrBuffer (/usr/lib/node_modules/bambu-cli/node_modules/readable-stream/lib/internal/streams/writable.js:334:12)
    at _write (/usr/lib/node_modules/bambu-cli/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
    at Writable.write (/usr/lib/node_modules/bambu-cli/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)

Node.js v20.10.0
root@BambuClient:~/.config/bambu-cli#`

**Comment by xDraconix** [comment]
I  added to status.js: 

' if (tray.cols!==undefined) { ... } '

this works for me.

**Comment by davglass** [comment]
I don't have direct access to an `A` series to test, but this should have been fixed in `v1.0.15`
